# Generated by Django 4.1.3 on 2022-11-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='premier_date',
            field=models.DateField(null=True),
        ),
    ]
