# Generated by Django 4.1.3 on 2022-11-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_premier_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='premier_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='premier date'),
        ),
    ]
