# Generated by Django 4.1.3 on 2022-11-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_login'),
        ('movies', '0008_alter_movie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='view_by',
            field=models.ManyToManyField(blank=True, related_name='movies_viewed', to='user.user'),
        ),
    ]
