# Generated by Django 4.1.3 on 2022-11-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movie_view_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
